<div class="col-md-6 text-center">
    <div class="small-box ">
        <a href="#" class="small-box-footer bg-info">2020</a>
        <div class="inner">
            <canvas id="chart-2020" width="700" height="400" style="background-color:rgba(255,255,255,1.00);border-radius:0px;width:700px;height:400px;padding-left:0px;padding-right:0px;padding-top:0px;padding-bottom:0px"></canvas>
        </div>
        <div class="icon">
            <i class="ion ion-bag"></i>
        </div>
        <a href="#" class="small-box-footer bg-danger">Cetak Laporan <i class="fas fa-print"></i></a>
    </div>
</div>

<div class="col-md-6 text-center">
    <div class="small-box ">
        <a href="#" class="small-box-footer bg-info">2021</a>
        <div class="inner">
            <canvas id="chart-2021" width="700" height="400" style="background-color:rgba(255,255,255,1.00);border-radius:0px;width:700px;height:400px;padding-left:0px;padding-right:0px;padding-top:0px;padding-bottom:0px"></canvas>
        </div>
        <div class="icon">
            <i class="ion ion-bag"></i>
        </div>
        <a href="#" class="small-box-footer bg-danger">Cetak Laporan <i class="fas fa-print"></i></a>
    </div>
</div>


<script>
    function MoreChartOptions() {}
    var ChartData = {
        labels: ["LPG",
            "PAKEM", "PENKUM", "JMS",
        ],
        datasets: [{
            fillColor: "rgba(52,152,219,1)",
            strokeColor: "rgba(52,152,219,0.5)",
            pointColor: "rgba(52,152,219,1)",
            markerShape: "circle",
            pointStrokeColor: "rgba(255,255,255,1.00)",
            data: [<?= explode('+', $c_hasil[0]['lpg'])[0];  ?>, <?= explode('+', $c_hasil[0]['pakem'])[0];  ?>, <?= explode('+', $c_hasil[0]['penkum'])[0];  ?>, <?= explode('+', $c_hasil[0]['jms'])[0];  ?>],
            title: "Target"
        }, {
            fillColor: "rgba(255,208,0,1)",
            strokeColor: "rgba(46,204,113,1)",
            pointColor: "rgba(46,204,113,1)",
            markerShape: "circle",
            pointStrokeColor: "rgba(255,255,255,1.00)",
            data: [<?= explode('+', $c_hasil[0]['lpg'])[1];  ?>, <?= explode('+', $c_hasil[0]['pakem'])[1];  ?>, <?= explode('+', $c_hasil[0]['penkum'])[1];  ?>, <?= explode('+', $c_hasil[0]['jms'])[1];  ?>],
            title: "Realisasi"
        }, {
            fillColor: "rgba(255,0,0,1)",
            strokeColor: "rgba(155,89,182,1)",
            pointColor: "rgba(155,89,182,1)",
            markerShape: "circle",
            pointStrokeColor: "rgba(255,255,255,1)",
            data: [<?= explode('+', $c_hasil[0]['lpg'])[2];  ?>, <?= explode('+', $c_hasil[0]['pakem'])[2];  ?>, <?= explode('+', $c_hasil[0]['penkum'])[2];  ?>, <?= explode('+', $c_hasil[0]['jms'])[2];  ?>],
            title: "Sisa Anggaran"
        }, ]
    };
    ChartOptions = {
        decimalSeparator: ".",
        thousandSeparator: ",",
        spaceLeft: 12,
        spaceRight: 12,
        spaceTop: 12,
        spaceBottom: 12,
        scaleLabel: "<%=value+''%>",
        yAxisMinimumInterval: 1,
        scaleShowLabels: true,
        scaleShowLine: true,
        scaleLineStyle: "solid",
        scaleLineWidth: 1,
        scaleLineColor: "rgba(0,0,0,0.6)",
        scaleOverlay: false,
        scaleOverride: false,
        scaleSteps: 10,
        scaleStepWidth: 10,
        scaleStartValue: 0,
        inGraphDataShow: true,
        inGraphDataTmpl: '<%=v3%>',
        inGraphDataFontFamily: "'Open Sans'",
        inGraphDataFontStyle: "normal bold",
        inGraphDataFontColor: "rgba(255,255,255,1.00)",
        inGraphDataFontSize: 12,
        inGraphDataPaddingX: 0,
        inGraphDataPaddingY: -5,
        inGraphDataAlign: "center",
        inGraphDataVAlign: "middle",
        inGraphDataXPosition: 2,
        inGraphDataYPosition: 2,
        inGraphDataAnglePosition: 2,
        inGraphDataRadiusPosition: 2,
        inGraphDataRotate: 90,
        inGraphDataPaddingAngle: 0,
        inGraphDataPaddingRadius: 0,
        inGraphDataBorders: false,
        inGraphDataBordersXSpace: 1,
        inGraphDataBordersYSpace: 1,
        inGraphDataBordersWidth: 1,
        inGraphDataBordersStyle: "solid",
        inGraphDataBordersColor: "rgba(0,0,0,1)",
        legend: true,
        maxLegendCols: 5,
        legendBlockSize: 15,
        legendFillColor: 'rgba(255,255,255,0.00)',
        legendColorIndicatorStrokeWidth: 1,
        legendPosX: -2,
        legendPosY: 4,
        legendXPadding: 0,
        legendYPadding: 0,
        legendBorders: false,
        legendBordersWidth: 1,
        legendBordersStyle: "solid",
        legendBordersColors: "rgba(102,102,102,1)",
        legendBordersSpaceBefore: 5,
        legendBordersSpaceLeft: 5,
        legendBordersSpaceRight: 5,
        legendBordersSpaceAfter: 5,
        legendSpaceBeforeText: 5,
        legendSpaceLeftText: 5,
        legendSpaceRightText: 5,
        legendSpaceAfterText: 5,
        legendSpaceBetweenBoxAndText: 5,
        legendSpaceBetweenTextHorizontal: 5,
        legendSpaceBetweenTextVertical: 5,
        legendFontFamily: "'Open Sans'",
        legendFontStyle: "normal normal",
        legendFontColor: "rgba(0,0,0,1)",
        legendFontSize: 15,
        showYAxisMin: false,
        rotateLabels: "smart",
        xAxisBottom: true,
        yAxisLeft: true,
        yAxisRight: false,
        scaleFontFamily: "'Open Sans'",
        scaleFontStyle: "normal normal",
        scaleFontColor: "rgba(0,0,0,1)",
        scaleFontSize: 12,
        pointLabelFontFamily: "'Open Sans'",
        pointLabelFontStyle: "normal normal",
        pointLabelFontColor: "rgba(102,102,102,1)",
        pointLabelFontSize: 12,
        angleShowLineOut: true,
        angleLineStyle: "solid",
        angleLineWidth: 1,
        angleLineColor: "rgba(0,0,0,0.1)",
        percentageInnerCutout: 50,
        scaleShowGridLines: true,
        scaleGridLineStyle: "solid",
        scaleGridLineWidth: 1,
        scaleGridLineColor: "rgba(0,0,0,0.1)",
        scaleXGridLinesStep: 1,
        scaleYGridLinesStep: 3,
        segmentShowStroke: true,
        segmentStrokeStyle: "solid",
        segmentStrokeWidth: 2,
        segmentStrokeColor: "rgba(255,255,255,1.00)",
        datasetStroke: true,
        datasetFill: true,
        datasetStrokeStyle: "solid",
        datasetStrokeWidth: 2,
        bezierCurve: true,
        bezierCurveTension: 0.4,
        pointDotStrokeStyle: "solid",
        pointDotStrokeWidth: 1,
        pointDotRadius: 3,
        pointDot: true,
        scaleTickSizeBottom: 5,
        scaleTickSizeTop: 5,
        scaleTickSizeLeft: 5,
        scaleTickSizeRight: 5,
        graphMin: 0,
        barShowStroke: false,
        barBorderRadius: 0,
        barStrokeStyle: "solid",
        barStrokeWidth: 1,
        barValueSpacing: 15,
        barDatasetSpacing: 0,
        scaleShowLabelBackdrop: true,
        scaleBackdropColor: 'rgba(255,255,255,0.75)',
        scaleBackdropPaddingX: 2,
        scaleBackdropPaddingY: 2,
        animationEasing: 'linear',
        animateRotate: true,
        animateScale: false,
        animationByDataset: false,
        animationLeftToRight: false,
        animationSteps: 80,
        animation: true,
        onAnimationComplete: function() {
            MoreChartOptions2()
        }
    };
    DrawTheChart(ChartData, ChartOptions, "chart-2020", "Bar");
</script>

<script>
    function MoreChartOptions() {}
    var ChartData = {
        labels: ["LPG",
            "PAKEM", "PENKUM", "JMS",
        ],
        datasets: [{
            fillColor: "rgba(52,152,219,1)",
            strokeColor: "rgba(52,152,219,0.5)",
            pointColor: "rgba(52,152,219,1)",
            markerShape: "circle",
            pointStrokeColor: "rgba(255,255,255,1.00)",
            data: [<?= explode('+', $c_hasil[1]['lpg'])[0];  ?>, <?= explode('+', $c_hasil[1]['pakem'])[0];  ?>, <?= explode('+', $c_hasil[1]['penkum'])[0];  ?>, <?= explode('+', $c_hasil[1]['jms'])[0];  ?>],
            title: "Target"
        }, {
            fillColor: "rgba(255,208,0,1)",
            strokeColor: "rgba(46,204,113,1)",
            pointColor: "rgba(46,204,113,1)",
            markerShape: "circle",
            pointStrokeColor: "rgba(255,255,255,1.00)",
            data: [<?= explode('+', $c_hasil[1]['lpg'])[1];  ?>, <?= explode('+', $c_hasil[1]['pakem'])[1];  ?>, <?= explode('+', $c_hasil[1]['penkum'])[1];  ?>, <?= explode('+', $c_hasil[1]['jms'])[1];  ?>],
            title: "Realisasi"
        }, {
            fillColor: "rgba(255,0,0,1)",
            strokeColor: "rgba(155,89,182,1)",
            pointColor: "rgba(155,89,182,1)",
            markerShape: "circle",
            pointStrokeColor: "rgba(255,255,255,1)",
            data: [<?= explode('+', $c_hasil[1]['lpg'])[2];  ?>, <?= explode('+', $c_hasil[1]['pakem'])[2];  ?>, <?= explode('+', $c_hasil[1]['penkum'])[2];  ?>, <?= explode('+', $c_hasil[1]['jms'])[2];  ?>],
            title: "Sisa Anggaran"
        }, ]
    };
    ChartOptions = {
        decimalSeparator: ".",
        thousandSeparator: ",",
        spaceLeft: 12,
        spaceRight: 12,
        spaceTop: 12,
        spaceBottom: 12,
        scaleLabel: "<%=value+''%>",
        yAxisMinimumInterval: 1,
        scaleShowLabels: true,
        scaleShowLine: true,
        scaleLineStyle: "solid",
        scaleLineWidth: 1,
        scaleLineColor: "rgba(0,0,0,0.6)",
        scaleOverlay: false,
        scaleOverride: false,
        scaleSteps: 10,
        scaleStepWidth: 10,
        scaleStartValue: 0,
        inGraphDataShow: true,
        inGraphDataTmpl: '<%=v3%>',
        inGraphDataFontFamily: "'Open Sans'",
        inGraphDataFontStyle: "normal bold",
        inGraphDataFontColor: "rgba(255,255,255,1.00)",
        inGraphDataFontSize: 12,
        inGraphDataPaddingX: 0,
        inGraphDataPaddingY: -5,
        inGraphDataAlign: "center",
        inGraphDataVAlign: "middle",
        inGraphDataXPosition: 2,
        inGraphDataYPosition: 2,
        inGraphDataAnglePosition: 2,
        inGraphDataRadiusPosition: 2,
        inGraphDataRotate: 90,
        inGraphDataPaddingAngle: 0,
        inGraphDataPaddingRadius: 0,
        inGraphDataBorders: false,
        inGraphDataBordersXSpace: 1,
        inGraphDataBordersYSpace: 1,
        inGraphDataBordersWidth: 1,
        inGraphDataBordersStyle: "solid",
        inGraphDataBordersColor: "rgba(0,0,0,1)",
        legend: true,
        maxLegendCols: 5,
        legendBlockSize: 15,
        legendFillColor: 'rgba(255,255,255,0.00)',
        legendColorIndicatorStrokeWidth: 1,
        legendPosX: -2,
        legendPosY: 4,
        legendXPadding: 0,
        legendYPadding: 0,
        legendBorders: false,
        legendBordersWidth: 1,
        legendBordersStyle: "solid",
        legendBordersColors: "rgba(102,102,102,1)",
        legendBordersSpaceBefore: 5,
        legendBordersSpaceLeft: 5,
        legendBordersSpaceRight: 5,
        legendBordersSpaceAfter: 5,
        legendSpaceBeforeText: 5,
        legendSpaceLeftText: 5,
        legendSpaceRightText: 5,
        legendSpaceAfterText: 5,
        legendSpaceBetweenBoxAndText: 5,
        legendSpaceBetweenTextHorizontal: 5,
        legendSpaceBetweenTextVertical: 5,
        legendFontFamily: "'Open Sans'",
        legendFontStyle: "normal normal",
        legendFontColor: "rgba(0,0,0,1)",
        legendFontSize: 15,
        showYAxisMin: false,
        rotateLabels: "smart",
        xAxisBottom: true,
        yAxisLeft: true,
        yAxisRight: false,
        scaleFontFamily: "'Open Sans'",
        scaleFontStyle: "normal normal",
        scaleFontColor: "rgba(0,0,0,1)",
        scaleFontSize: 12,
        pointLabelFontFamily: "'Open Sans'",
        pointLabelFontStyle: "normal normal",
        pointLabelFontColor: "rgba(102,102,102,1)",
        pointLabelFontSize: 12,
        angleShowLineOut: true,
        angleLineStyle: "solid",
        angleLineWidth: 1,
        angleLineColor: "rgba(0,0,0,0.1)",
        percentageInnerCutout: 50,
        scaleShowGridLines: true,
        scaleGridLineStyle: "solid",
        scaleGridLineWidth: 1,
        scaleGridLineColor: "rgba(0,0,0,0.1)",
        scaleXGridLinesStep: 1,
        scaleYGridLinesStep: 3,
        segmentShowStroke: true,
        segmentStrokeStyle: "solid",
        segmentStrokeWidth: 2,
        segmentStrokeColor: "rgba(255,255,255,1.00)",
        datasetStroke: true,
        datasetFill: true,
        datasetStrokeStyle: "solid",
        datasetStrokeWidth: 2,
        bezierCurve: true,
        bezierCurveTension: 0.4,
        pointDotStrokeStyle: "solid",
        pointDotStrokeWidth: 1,
        pointDotRadius: 3,
        pointDot: true,
        scaleTickSizeBottom: 5,
        scaleTickSizeTop: 5,
        scaleTickSizeLeft: 5,
        scaleTickSizeRight: 5,
        graphMin: 0,
        barShowStroke: false,
        barBorderRadius: 0,
        barStrokeStyle: "solid",
        barStrokeWidth: 1,
        barValueSpacing: 15,
        barDatasetSpacing: 0,
        scaleShowLabelBackdrop: true,
        scaleBackdropColor: 'rgba(255,255,255,0.75)',
        scaleBackdropPaddingX: 2,
        scaleBackdropPaddingY: 2,
        animationEasing: 'linear',
        animateRotate: true,
        animateScale: false,
        animationByDataset: false,
        animationLeftToRight: false,
        animationSteps: 80,
        animation: true,
        onAnimationComplete: function() {
            MoreChartOptions2()
        }
    };
    DrawTheChart(ChartData, ChartOptions, "chart-2021", "Bar");
</script>